/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  BigNumberish,
  Overrides,
} from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Voter, VoterInterface } from "../../../contracts/test/Voter";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract NounsDAOLogicV2",
        name: "dao_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "proposalId_",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "support_",
        type: "uint8",
      },
      {
        internalType: "bool",
        name: "useReason_",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "castVote",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "dao",
    outputs: [
      {
        internalType: "contract NounsDAOLogicV2",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "proposalId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "support",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516102d13803806102d183398101604081905261002f9161007d565b600080546001600160a01b039095166001600160a01b031990951694909417909355600191909155600280549215156101000261ffff1990931660ff909216919091179190911790556100e9565b6000806000806080858703121561009357600080fd5b84516001600160a01b03811681146100aa57600080fd5b60208601516040870151919550935060ff811681146100c857600080fd5b606086015190925080151581146100de57600080fd5b939692955090935050565b6101d9806100f86000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80630fb524ce14610051578063119f87471461005b5780632dfca4451461007f5780634162169f14610096575b600080fd5b6100596100c1565b005b6002546100689060ff1681565b60405160ff90911681526020015b60405180910390f35b61008860015481565b604051908152602001610076565b6000546100a9906001600160a01b031681565b6040516001600160a01b039091168152602001610076565b600254610100900460ff1615610163576000546001546002546040516364c0599560e01b8152600481019290925260ff16602482015260606044820152600b60648201526a39b7b6b2903932b0b9b7b760a91b60848201526001600160a01b03909116906364c059959060a4015b600060405180830381600087803b15801561014957600080fd5b505af115801561015d573d6000803e3d6000fd5b50505050565b60005460015460025460405163227d647b60e11b8152600481019290925260ff1660248201526001600160a01b03909116906344fac8f69060440161012f56fea26469706673582212200ffe3ee5c511d48883dc2a2971aa174b06449367f084fee24b933bc46fe3f9b764736f6c63430008130033";

type VoterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: VoterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Voter__factory extends ContractFactory {
  constructor(...args: VoterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    dao_: string,
    proposalId_: BigNumberish,
    support_: BigNumberish,
    useReason_: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Voter> {
    return super.deploy(
      dao_,
      proposalId_,
      support_,
      useReason_,
      overrides || {}
    ) as Promise<Voter>;
  }
  override getDeployTransaction(
    dao_: string,
    proposalId_: BigNumberish,
    support_: BigNumberish,
    useReason_: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(
      dao_,
      proposalId_,
      support_,
      useReason_,
      overrides || {}
    );
  }
  override attach(address: string): Voter {
    return super.attach(address) as Voter;
  }
  override connect(signer: Signer): Voter__factory {
    return super.connect(signer) as Voter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): VoterInterface {
    return new utils.Interface(_abi) as VoterInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Voter {
    return new Contract(address, _abi, signerOrProvider) as Voter;
  }
}
