/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as base from "./base";
export { INounsTokenFork__factory } from "./INounsTokenFork__factory";
export { NounsTokenFork__factory } from "./NounsTokenFork__factory";
