/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IForkDAODeployer,
  IForkDAODeployerInterface,
} from "../../../../contracts/governance/NounsDAOInterfaces.sol/IForkDAODeployer";

const _abi = [
  {
    inputs: [],
    name: "auctionImpl",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "forkingPeriodEndTimestamp",
        type: "uint256",
      },
      {
        internalType: "contract INounsDAOForkEscrow",
        name: "forkEscrowAddress",
        type: "address",
      },
    ],
    name: "deployForkDAO",
    outputs: [
      {
        internalType: "address",
        name: "treasury",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "governorImpl",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tokenImpl",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "treasuryImpl",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IForkDAODeployer__factory {
  static readonly abi = _abi;
  static createInterface(): IForkDAODeployerInterface {
    return new utils.Interface(_abi) as IForkDAODeployerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IForkDAODeployer {
    return new Contract(address, _abi, signerOrProvider) as IForkDAODeployer;
  }
}
