/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  NounsDAOStorageV1Adjusted,
  NounsDAOStorageV1AdjustedInterface,
} from "../../../../contracts/governance/NounsDAOInterfaces.sol/NounsDAOStorageV1Adjusted";

const _abi = [
  {
    inputs: [],
    name: "admin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "latestProposalIds",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nouns",
    outputs: [
      {
        internalType: "contract NounsTokenLike",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingAdmin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "proposalCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "proposalThresholdBPS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "quorumVotesBPS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "timelock",
    outputs: [
      {
        internalType: "contract INounsDAOExecutor",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "vetoer",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "votingDelay",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "votingPeriod",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610209806100206000396000f3fe608060405234801561001057600080fd5b50600436106100b45760003560e01c80635c60da1b116100715780635c60da1b1461014557806383cce0e114610158578063d33219b414610161578063d8bff44014610174578063da35c66414610187578063f851a4401461019057600080fd5b806302a251a3146100b957806314a67ea4146100d557806317977c61146100de57806326782247146100fe5780632de45f18146101295780633932abb11461013c575b600080fd5b6100c260055481565b6040519081526020015b60405180910390f35b6100c260065481565b6100c26100ec3660046101a3565b600c6020526000908152604090205481565b600154610111906001600160a01b031681565b6040516001600160a01b0390911681526020016100cc565b600a54610111906001600160a01b031681565b6100c260045481565b600254610111906001600160a01b031681565b6100c260075481565b600954610111906001600160a01b031681565b600354610111906001600160a01b031681565b6100c260085481565b600054610111906001600160a01b031681565b6000602082840312156101b557600080fd5b81356001600160a01b03811681146101cc57600080fd5b939250505056fea26469706673582212202105ca51c5860247787a7a2b381e73deee6ca668473b8ba1b8154c0334cb992a64736f6c63430008130033";

type NounsDAOStorageV1AdjustedConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NounsDAOStorageV1AdjustedConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class NounsDAOStorageV1Adjusted__factory extends ContractFactory {
  constructor(...args: NounsDAOStorageV1AdjustedConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<NounsDAOStorageV1Adjusted> {
    return super.deploy(overrides || {}) as Promise<NounsDAOStorageV1Adjusted>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): NounsDAOStorageV1Adjusted {
    return super.attach(address) as NounsDAOStorageV1Adjusted;
  }
  override connect(signer: Signer): NounsDAOStorageV1Adjusted__factory {
    return super.connect(signer) as NounsDAOStorageV1Adjusted__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NounsDAOStorageV1AdjustedInterface {
    return new utils.Interface(_abi) as NounsDAOStorageV1AdjustedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NounsDAOStorageV1Adjusted {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as NounsDAOStorageV1Adjusted;
  }
}
