/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as base from "./base";
export type { base };
export type { INounsTokenFork } from "./INounsTokenFork";
export type { NounsTokenFork } from "./NounsTokenFork";
