/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  INounsDAO,
  INounsDAOInterface,
} from "../../../../../contracts/governance/data/NounsDAOData.sol/INounsDAO";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "proposalId",
        type: "uint256",
      },
    ],
    name: "proposalsV3",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "proposer",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "proposalThreshold",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "quorumVotes",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "eta",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "startBlock",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "endBlock",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "forVotes",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "againstVotes",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "abstainVotes",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "canceled",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "vetoed",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "executed",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "totalSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "creationBlock",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "signers",
            type: "address[]",
          },
          {
            internalType: "uint256",
            name: "updatePeriodEndBlock",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "objectionPeriodEndBlock",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "executeOnTimelockV1",
            type: "bool",
          },
        ],
        internalType: "struct NounsDAOStorageV3.ProposalCondensed",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class INounsDAO__factory {
  static readonly abi = _abi;
  static createInterface(): INounsDAOInterface {
    return new utils.Interface(_abi) as INounsDAOInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INounsDAO {
    return new Contract(address, _abi, signerOrProvider) as INounsDAO;
  }
}
