/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as nounsDaoDataSol from "./NounsDAOData.sol";
export { NounsDAODataEvents__factory } from "./NounsDAODataEvents__factory";
export { NounsDAODataProxy__factory } from "./NounsDAODataProxy__factory";
